import 'package:auto_route/auto_route.dart';
import 'package:datn_mobile/core/router/router.gr.dart';
import 'package:datn_mobile/core/theme/app_theme.dart';
import 'package:datn_mobile/features/generate/states/models_controller_pod.dart';
import 'package:datn_mobile/features/generate/domain/entity/ai_model.dart';
import 'package:datn_mobile/features/generate/states/controller_provider.dart';
import 'package:datn_mobile/features/generate/ui/widgets/generate/generation_settings_sheet.dart';
import 'package:datn_mobile/features/generate/ui/widgets/generate/option_chip.dart';
import 'package:datn_mobile/features/generate/ui/widgets/generate/topic_input_bar.dart';
import 'package:datn_mobile/features/generate/ui/widgets/generate/topic_suggestions.dart';
import 'package:datn_mobile/shared/utils/snackbar_utils.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:wolt_modal_sheet/wolt_modal_sheet.dart';

/// Available languages for presentation generation
const List<String> _availableLanguages = ['English', 'Vietnamese'];

/// Available slide counts for presentation generation
const List<int> _availableSlideCounts = [3, 4, 5, 7, 10, 12, 15, 20, 25, 30];

/// Generator types available in the app
enum GeneratorType {
  presentation('Presentation', Icons.slideshow_rounded),
  image('Image', Icons.image_rounded),
  mindmap('Mindmap', Icons.account_tree_rounded);

  final String label;
  final IconData icon;

  const GeneratorType(this.label, this.icon);
}

@RoutePage()
class PresentationGeneratePage extends ConsumerStatefulWidget {
  const PresentationGeneratePage({super.key});

  @override
  ConsumerState<PresentationGeneratePage> createState() =>
      _PresentationGeneratePageState();
}

class _PresentationGeneratePageState
    extends ConsumerState<PresentationGeneratePage> {
  final TextEditingController _topicController = TextEditingController();
  final FocusNode _topicFocusNode = FocusNode();
  GeneratorType _selectedGenerator = GeneratorType.presentation;

  @override
  void initState() {
    super.initState();
    // Initialize controller with current topic from state
    final formState = ref.read(presentationFormControllerProvider);
    _topicController.text = formState.topic;

    // Listen for text changes and update state
    _topicController.addListener(_onTopicChanged);

    // Pre-fetch models and set default if not already set
    _initializeDefaultModel();
  }

  Future<void> _initializeDefaultModel() async {
    final formState = ref.read(presentationFormControllerProvider);
    if (formState.outlineModel == null) {
      // Fetch text models and get default
      final modelsState = await ref.read(
        modelsControllerPod(ModelType.text).future,
      );
      final defaultModel = modelsState.availableModels
          .where((m) => m.isDefault && m.isEnabled)
          .firstOrNull;
      if (defaultModel != null && mounted) {
        ref
            .read(presentationFormControllerProvider.notifier)
            .updateOutlineModel(defaultModel);
      }
    }
  }

  @override
  void dispose() {
    _topicController.removeListener(_onTopicChanged);
    _topicController.dispose();
    _topicFocusNode.dispose();
    super.dispose();
  }

  void _onTopicChanged() {
    ref
        .read(presentationFormControllerProvider.notifier)
        .updateTopic(_topicController.text);
  }

  @override
  Widget build(BuildContext context) {
    final cs = Theme.of(context).colorScheme;

    // Listen for generation completion using request ID pattern
    ref.listen(presentationGenerateControllerProvider, (previous, next) {
      next.when(
        data: (state) {
          // Check if a new outline was generated by comparing request IDs
          final previousOutlineRequestId = previous?.when(
            data: (prevState) => prevState.lastProcessedOutlineRequestId,
            loading: () => null,
            error: (_, _) => null,
          );
          final hasNewOutline =
              state.lastProcessedOutlineRequestId != null &&
              state.lastProcessedOutlineRequestId != previousOutlineRequestId;

          if (hasNewOutline && state.outlineResponse != null) {
            // Save outline to form state
            ref
                .read(presentationFormControllerProvider.notifier)
                .setOutline(state.outlineResponse!);
            // Navigate to customization page
            if (context.router.current.name == PresentationGenerateRoute.name) {
              context.router.push(const PresentationCustomizationRoute());
            } else {
              context.router.replace(const PresentationCustomizationRoute());
            }
          }
        },
        loading: () {},
        error: (error, stackTrace) {
          if (context.mounted) {
            SnackbarUtils.showError(context, 'Error: $error');
          }
        },
      );
    });

    return Scaffold(
      backgroundColor: context.isDarkMode
          ? cs.surface
          : const Color(0xFFF9FAFB),
      body: SafeArea(
        child: Column(
          children: [
            // App Bar
            _buildAppBar(context),
            // Main Content
            Expanded(child: _buildMainContent(context)),
            // Bottom Input Section
            TopicInputBar(
              topicController: _topicController,
              topicFocusNode: _topicFocusNode,
              onAttachFile: _handleAttachFile,
              onGenerate: _handleGenerate,
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildAppBar(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
      decoration: ThemeDecorations.containerWithBottomBorder(context),
      child: Row(
        children: [
          IconButton(
            onPressed: () => context.router.maybePop(),
            icon: const Icon(Icons.arrow_back_ios_new, size: 20),
            padding: EdgeInsets.zero,
            constraints: const BoxConstraints(),
          ),
          const SizedBox(width: 12),
          // Generator type dropdown
          Expanded(child: _buildGeneratorDropdown(context)),
          IconButton(
            onPressed: () => GenerationSettingsSheet.show(context),
            icon: Icon(Icons.tune_rounded, color: context.secondaryTextColor),
          ),
        ],
      ),
    );
  }

  Widget _buildGeneratorDropdown(BuildContext context) {
    return GestureDetector(
      onTap: () => _showGeneratorPicker(context),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Icon(
            _selectedGenerator.icon,
            size: 20,
            color: Theme.of(context).colorScheme.primary,
          ),
          const SizedBox(width: 8),
          Text(
            _selectedGenerator.label,
            style: TextStyle(
              fontSize: 18,
              fontWeight: FontWeight.w600,
              color: context.isDarkMode ? Colors.white : Colors.grey[900],
            ),
          ),
          const SizedBox(width: 4),
          Icon(
            Icons.keyboard_arrow_down_rounded,
            size: 24,
            color: context.secondaryTextColor,
          ),
        ],
      ),
    );
  }

  void _showGeneratorPicker(BuildContext context) {
    showModalBottomSheet(
      context: context,
      backgroundColor: context.surfaceColor,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
      ),
      builder: (bottomSheetContext) => Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          const SizedBox(height: 12),
          // Handle
          Container(
            width: 40,
            height: 4,
            decoration: BoxDecoration(
              color: bottomSheetContext.dividerColor,
              borderRadius: BorderRadius.circular(2),
            ),
          ),
          const SizedBox(height: 16),
          // Title
          Text(
            'Select Generator',
            style: TextStyle(
              fontSize: 18,
              fontWeight: FontWeight.bold,
              color: bottomSheetContext.isDarkMode
                  ? Colors.white
                  : Colors.grey[900],
            ),
          ),
          const SizedBox(height: 8),
          // Options
          ...GeneratorType.values.map((type) {
            final isSelected = _selectedGenerator == type;
            return ListTile(
              leading: Container(
                width: 40,
                height: 40,
                decoration: BoxDecoration(
                  color: isSelected
                      ? Theme.of(
                          bottomSheetContext,
                        ).colorScheme.primary.withValues(alpha: 0.1)
                      : bottomSheetContext.secondarySurfaceColor,
                  borderRadius: BorderRadius.circular(10),
                ),
                child: Icon(
                  type.icon,
                  color: isSelected
                      ? Theme.of(bottomSheetContext).colorScheme.primary
                      : bottomSheetContext.secondaryTextColor,
                ),
              ),
              title: Text(
                type.label,
                style: TextStyle(
                  fontWeight: isSelected ? FontWeight.w600 : FontWeight.w500,
                  color: bottomSheetContext.isDarkMode
                      ? Colors.white
                      : Colors.grey[900],
                ),
              ),
              trailing: isSelected
                  ? Icon(
                      Icons.check_circle_rounded,
                      color: Theme.of(bottomSheetContext).colorScheme.primary,
                    )
                  : null,
              onTap: () {
                Navigator.pop(bottomSheetContext);
                _onGeneratorTypeChanged(type);
              },
            );
          }),
          SizedBox(
            height: MediaQuery.of(bottomSheetContext).padding.bottom + 16,
          ),
        ],
      ),
    );
  }

  void _onGeneratorTypeChanged(GeneratorType type) {
    if (_selectedGenerator != type) {
      setState(() {
        _selectedGenerator = type;
      });
      // TODO: Navigate to the appropriate generator page or update UI
      // For now, show a snackbar for non-presentation generators
      if (type != GeneratorType.presentation) {
        SnackbarUtils.showInfo(context, '${type.label} generator coming soon!');
      }
    }
  }

  Widget _buildMainContent(BuildContext context) {
    final formState = ref.watch(presentationFormControllerProvider);

    return SingleChildScrollView(
      padding: const EdgeInsets.all(20),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          const SizedBox(height: 40),
          // Icon
          Container(
            width: 80,
            height: 80,
            decoration: BoxDecoration(
              gradient: LinearGradient(
                colors: [
                  Theme.of(context).colorScheme.primary,
                  Theme.of(context).colorScheme.secondary,
                ],
                begin: Alignment.topLeft,
                end: Alignment.bottomRight,
              ),
              borderRadius: BorderRadius.circular(20),
            ),
            child: const Icon(
              Icons.auto_awesome,
              size: 40,
              color: Colors.white,
            ),
          ),
          const SizedBox(height: 24),
          // Title
          Text(
            'AI Presentation Generator',
            style: TextStyle(
              fontSize: 24,
              fontWeight: FontWeight.bold,
              color: context.isDarkMode ? Colors.white : Colors.grey[900],
            ),
          ),
          const SizedBox(height: 12),
          // Subtitle
          Text(
            'Enter your topic and let AI create a professional presentation for you',
            textAlign: TextAlign.center,
            style: TextStyle(fontSize: 14, color: context.secondaryTextColor),
          ),
          const SizedBox(height: 40),
          // Options Row
          _buildOptionsRow(context, formState),
          const SizedBox(height: 20),
          // Quick Suggestions
          TopicSuggestions(
            onSuggestionTap: (suggestion) {
              _topicController.text = suggestion;
            },
          ),
        ],
      ),
    );
  }

  Widget _buildOptionsRow(BuildContext context, dynamic formState) {
    final formController = ref.read(
      presentationFormControllerProvider.notifier,
    );

    return Wrap(
      spacing: 12,
      runSpacing: 12,
      alignment: WrapAlignment.center,
      children: [
        // Slide Count
        OptionChip(
          icon: Icons.format_list_numbered,
          label: '${formState.slideCount} slides',
          onTap: () => _showSlideCountPicker(formController, formState),
        ),
        // Language
        OptionChip(
          icon: Icons.language,
          label: formState.language,
          onTap: () => _showLanguagePicker(formController, formState),
        ),
        // Model
        OptionChip(
          icon: Icons.psychology,
          label: formState.outlineModel?.displayName ?? 'Select Model',
          onTap: () => _showModelPicker(formController, formState),
        ),
      ],
    );
  }

  // Removed _buildOptionChip - now using OptionChip widget
  // Removed _buildSuggestions - now using TopicSuggestions widget
  // Removed _buildBottomInputSection - now using TopicInputBar widget

  void _showSlideCountPicker(dynamic formController, dynamic formState) {
    _showPickerBottomSheet(
      title: 'Select Slide Count',
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: _availableSlideCounts.map((count) {
          final isSelected = formState.slideCount == count;
          return ListTile(
            title: Text('$count slides'),
            trailing: isSelected
                ? Icon(
                    Icons.check_circle_rounded,
                    color: Theme.of(context).colorScheme.primary,
                  )
                : null,
            onTap: () {
              formController.updateSlideCount(count);
              Navigator.pop(context);
            },
          );
        }).toList(),
      ),
    );
  }

  void _showLanguagePicker(dynamic formController, dynamic formState) {
    _showPickerBottomSheet(
      title: 'Select Language',
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: _availableLanguages.map((language) {
          final isSelected = formState.language == language;
          return ListTile(
            title: Text(language),
            trailing: isSelected
                ? Icon(
                    Icons.check_circle_rounded,
                    color: Theme.of(context).colorScheme.primary,
                  )
                : null,
            onTap: () {
              formController.updateLanguage(language);
              Navigator.pop(context);
            },
          );
        }).toList(),
      ),
    );
  }

  void _showModelPicker(dynamic formController, dynamic formState) {
    _showPickerBottomSheet(
      title: 'Select AI Model',
      child: Consumer(
        builder: (context, ref, _) {
          final modelsAsync = ref.watch(modelsControllerPod(ModelType.text));
          return modelsAsync.when(
            data: (state) {
              final models = state.availableModels
                  .where((m) => m.isEnabled)
                  .toList();
              if (models.isEmpty) {
                return const Padding(
                  padding: EdgeInsets.all(20),
                  child: Text('No models available'),
                );
              }
              return Column(
                mainAxisSize: MainAxisSize.min,
                children: models.map((model) {
                  final isSelected =
                      formState.outlineModel?.displayName == model.displayName;
                  return ListTile(
                    title: Text(model.displayName),
                    trailing: isSelected
                        ? Icon(
                            Icons.check_circle_rounded,
                            color: Theme.of(context).colorScheme.primary,
                          )
                        : null,
                    onTap: () {
                      formController.updateOutlineModel(model);
                      Navigator.pop(context);
                    },
                  );
                }).toList(),
              );
            },
            loading: () => const Padding(
              padding: EdgeInsets.all(20),
              child: Center(child: CircularProgressIndicator()),
            ),
            error: (_, _) => const Padding(
              padding: EdgeInsets.all(20),
              child: Text('Failed to load models'),
            ),
          );
        },
      ),
    );
  }

  void _handleGenerate() {
    _topicFocusNode.unfocus();
    final formController = ref.read(
      presentationFormControllerProvider.notifier,
    );
    final outlineData = formController.toOutlineData();
    ref
        .read(presentationGenerateControllerProvider.notifier)
        .generateOutline(outlineData);
  }

  void _handleAttachFile() {
    showModalBottomSheet(
      context: context,
      backgroundColor: context.surfaceColor,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
      ),
      builder: (bottomSheetContext) => Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          const SizedBox(height: 12),
          // Handle
          Container(
            width: 40,
            height: 4,
            decoration: BoxDecoration(
              color: bottomSheetContext.dividerColor,
              borderRadius: BorderRadius.circular(2),
            ),
          ),
          const SizedBox(height: 16),
          // Title
          Text(
            'Attach Files',
            style: TextStyle(
              fontSize: 18,
              fontWeight: FontWeight.bold,
              color: bottomSheetContext.isDarkMode
                  ? Colors.white
                  : Colors.grey[900],
            ),
          ),
          const SizedBox(height: 8),
          // Options
          ListTile(
            leading: Container(
              width: 40,
              height: 40,
              decoration: BoxDecoration(
                color: Colors.blue.withValues(alpha: 0.1),
                borderRadius: BorderRadius.circular(10),
              ),
              child: const Icon(Icons.description_outlined, color: Colors.blue),
            ),
            title: const Text('Document'),
            subtitle: const Text('PDF, Word, PowerPoint'),
            onTap: () {
              Navigator.pop(bottomSheetContext);
              // TODO: Implement document picker
              if (mounted) {
                SnackbarUtils.showInfo(context, 'Document picker coming soon!');
              }
            },
          ),
          ListTile(
            leading: Container(
              width: 40,
              height: 40,
              decoration: BoxDecoration(
                color: Colors.green.withValues(alpha: 0.1),
                borderRadius: BorderRadius.circular(10),
              ),
              child: const Icon(Icons.image_outlined, color: Colors.green),
            ),
            title: const Text('Image'),
            subtitle: const Text('PNG, JPG, GIF'),
            onTap: () {
              Navigator.pop(bottomSheetContext);
              // TODO: Implement image picker
              if (mounted) {
                SnackbarUtils.showInfo(context, 'Image picker coming soon!');
              }
            },
          ),
          ListTile(
            leading: Container(
              width: 40,
              height: 40,
              decoration: BoxDecoration(
                color: Colors.orange.withValues(alpha: 0.1),
                borderRadius: BorderRadius.circular(10),
              ),
              child: const Icon(Icons.link_rounded, color: Colors.orange),
            ),
            title: const Text('Link'),
            subtitle: const Text('Website URL'),
            onTap: () {
              Navigator.pop(bottomSheetContext);
              // TODO: Implement link input
              if (mounted) {
                SnackbarUtils.showInfo(context, 'Link input coming soon!');
              }
            },
          ),
          SizedBox(
            height: MediaQuery.of(bottomSheetContext).padding.bottom + 16,
          ),
        ],
      ),
    );
  }

  void _showPickerBottomSheet({required String title, required Widget child}) {
    final isDark = Theme.of(context).brightness == Brightness.dark;

    WoltModalSheet.show<void>(
      context: context,
      modalTypeBuilder: (context) => WoltModalType.bottomSheet(),
      useSafeArea: true,
      pageListBuilder: (modelBottomSheetContext) {
        return [
          SliverWoltModalSheetPage(
            trailingNavBarWidget: IconButton(
              onPressed: () => Navigator.pop(modelBottomSheetContext),
              padding: const EdgeInsets.symmetric(horizontal: 16),
              icon: Icon(
                Icons.close_rounded,
                color: isDark ? Colors.grey[400] : Colors.grey[600],
              ),
            ),
            pageTitle: Center(
              child: Padding(
                padding: const EdgeInsets.symmetric(horizontal: 16),
                child: Text(
                  title,
                  style: TextStyle(
                    color: isDark ? Colors.white : Colors.grey[900],
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ),
            ),
            mainContentSliversBuilder: (context) => [
              SliverPadding(
                padding: const EdgeInsets.all(20),
                sliver: SliverToBoxAdapter(child: child),
              ),
            ],
          ),
        ];
      },
    );
  }
}
